version: '3.4'

services:
  stocktradingapp:
    image: stocktradingapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
